# Generated by Django 3.0.5 on 2020-04-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('no', models.IntegerField(db_column='bno', primary_key=True, serialize=False, verbose_name='书籍编号')),
                ('name', models.CharField(db_column='bname', max_length=64, verbose_name='书籍')),
                ('author', models.CharField(db_column='bauthor', max_length=64, verbose_name='作者')),
                ('pub_house', models.CharField(max_length=100, verbose_name='出版社')),
                ('pub_date', models.DateTimeField(null=True, verbose_name='出版日期')),
            ],
            options={
                'verbose_name': '图书',
                'verbose_name_plural': '图书',
                'db_table': 'tb_book',
            },
        ),
    ]
